/**
 * Grade Service API Client
 *
 * All calls go through same-origin Next.js proxy routes which forward the
 * HttpOnly JWT to the backend Grade microservice (mounted at /api/grades).
 * No dynamic route segments are used on the client; identifiers are passed
 * via query string.
 *
 * Backend endpoints:
 *  - GET    /grades/my            (Student) own grades + summaries
 *  - GET    /grades/my/export     (Student) PDF transcript
 *  - POST   /grades               (Teacher) body { studentId, courseId, value, type, ... }
 *  - GET    /grades               (Teacher) grades of their own courses
 *  - PUT    /grades/:id           (Teacher)
 *  - DELETE /grades/:id           (Teacher)
 */

import { apiClient } from "./client"
import type {
  Grade,
  GradeFormData,
  GradeQueryParams,
  GradesListResponse,
  GradeSummary,
} from "@/types/grade"

const GRADES_BASE = "/api/grades"

export interface GradeApiResult<T = unknown> {
  success: boolean
  data?: T
  error?: string
  status?: number
}

// ---- Response normalization ----------------------------------------------
// The backend may return either a bare array or a wrapped payload
// ({ grades: [...], summaries: [...], overallAverage }). Normalize both
// shapes so the UI always receives the wrapped form.

function normalizeGrades(data: unknown): GradesListResponse {
  if (Array.isArray(data)) return { grades: data as Grade[] }
  const obj = (data ?? {}) as Record<string, unknown>
  return {
    grades: Array.isArray(obj.grades) ? (obj.grades as Grade[]) : [],
    summaries: Array.isArray(obj.summaries) ? (obj.summaries as GradeSummary[]) : undefined,
    overallAverage:
      typeof obj.overallAverage === "number" ? obj.overallAverage : undefined,
    total: typeof obj.total === "number" ? obj.total : undefined,
  }
}

function buildQuery(params?: GradeQueryParams): string {
  const searchParams = new URLSearchParams()
  if (params?.courseId) searchParams.set("courseId", params.courseId)
  if (params?.studentId) searchParams.set("studentId", params.studentId)
  if (params?.semester) searchParams.set("semester", params.semester)
  if (params?.academicYear) searchParams.set("academicYear", params.academicYear)
  if (params?.type) searchParams.set("type", params.type)
  const query = searchParams.toString()
  return query ? `?${query}` : ""
}

// ---- Student --------------------------------------------------------------

export async function getMyGradesApi(
  params?: GradeQueryParams
): Promise<GradeApiResult<GradesListResponse>> {
  const response = await apiClient.get<unknown>(`${GRADES_BASE}/my${buildQuery(params)}`)
  return {
    success: !response.error,
    data: response.error ? undefined : normalizeGrades(response.data),
    error: response.error?.message,
    status: response.error?.status,
  }
}

// Download the PDF transcript generated by the backend. Calls fetch directly
// (not the JSON apiClient) because the response is a binary document.
export async function exportMyGradesApi(
  params?: GradeQueryParams
): Promise<GradeApiResult<Blob>> {
  try {
    const response = await fetch(`${GRADES_BASE}/my/export${buildQuery(params)}`, {
      credentials: "include",
    })
    if (!response.ok) {
      const data = await response.json().catch(() => ({}))
      return {
        success: false,
        error: data.message || data.error || `Export failed with status ${response.status}`,
        status: response.status,
      }
    }
    const blob = await response.blob()
    return { success: true, data: blob, status: response.status }
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : "Network error",
    }
  }
}

// ---- Teacher ---------------------------------------------------------------

export async function getGradesApi(
  params?: GradeQueryParams
): Promise<GradeApiResult<GradesListResponse>> {
  const response = await apiClient.get<unknown>(`${GRADES_BASE}${buildQuery(params)}`)
  return {
    success: !response.error,
    data: response.error ? undefined : normalizeGrades(response.data),
    error: response.error?.message,
    status: response.error?.status,
  }
}

export async function createGradeApi(data: GradeFormData): Promise<GradeApiResult<Grade>> {
  const response = await apiClient.post<{ grade?: Grade } | Grade>(GRADES_BASE, data)
  const resData = response.data
  const grade =
    resData && "grade" in (resData as object)
      ? (resData as { grade: Grade }).grade
      : (resData as Grade | undefined)
  return {
    success: !response.error,
    data: grade,
    error: response.error?.message,
    status: response.error?.status,
  }
}

export async function updateGradeApi(
  gradeId: string,
  data: Partial<GradeFormData>
): Promise<GradeApiResult<Grade>> {
  const response = await apiClient.put<{ grade?: Grade } | Grade>(
    `${GRADES_BASE}?id=${encodeURIComponent(gradeId)}`,
    data
  )
  const resData = response.data
  const grade =
    resData && "grade" in (resData as object)
      ? (resData as { grade: Grade }).grade
      : (resData as Grade | undefined)
  return {
    success: !response.error,
    data: grade,
    error: response.error?.message,
    status: response.error?.status,
  }
}

export async function deleteGradeApi(gradeId: string): Promise<GradeApiResult> {
  const response = await apiClient.delete(`${GRADES_BASE}?id=${encodeURIComponent(gradeId)}`)
  return {
    success: !response.error,
    error: response.error?.message,
    status: response.error?.status,
  }
}
