/**
 * Absence Service domain types.
 *
 * Mirrors the backend Absence service data model (SessionQRCode,
 * AttendanceScan, Absence, JustificationRequest). All identifiers are Mongo
 * ObjectId strings on the wire.
 */

// ---- Enums --------------------------------------------------------------

export type AttendanceStatus = "present"

// Absence lifecycle: auto-created "absent" -> "justified" (justification
// submitted, pending review) -> "confirmed" (approved) or back to "absent"
// (rejected).
export type AbsenceStatus = "absent" | "justified" | "confirmed"

// Justification review decision.
export type JustificationDecision = "pending" | "approved" | "rejected"

// ---- Entities -----------------------------------------------------------

export interface SessionQRCode {
  _id: string
  scheduleId: string
  courseId: string
  sessionDate: string
  token: string
  validFrom: string
  validUntil: string
  isActive: boolean
  // Optional denormalized fields the backend may include for display.
  courseName?: string
  courseCode?: string
  roomName?: string
}

export interface AttendanceScan {
  _id: string
  qrCodeId: string
  studentId: string
  scannedAt: string
  status: AttendanceStatus
}

export interface Absence {
  _id: string
  studentId: string
  courseId: string
  scheduleId: string
  campusId: string
  sessionDate: string
  status: AbsenceStatus
  autoGeneratedAt: string
  // Optional denormalized display fields.
  courseName?: string
  courseCode?: string
  studentName?: string
  studentEmail?: string
  // Present when a justification has been submitted for this absence.
  justification?: JustificationRequest
}

export interface JustificationRequest {
  _id: string
  absenceId: string
  studentId: string
  documentUrl: string
  reason: string
  submittedAt: string
  reviewedBy?: string
  reviewedAt?: string
  decision: JustificationDecision
  rejectionNote?: string
  // Optional denormalized fields for the reviewer's queue view.
  absence?: Absence
  studentName?: string
  studentEmail?: string
  courseName?: string
  sessionDate?: string
}

// ---- Request / Response payloads ----------------------------------------

// Student scans a QR code -> POST attendance scan.
export interface ScanQRRequest {
  qrToken: string
}

export interface ScanQRResponse {
  message: string
  scan?: AttendanceScan
}

// The active QR code for a session, as shown to/scanned by the student.
export interface ActiveQRResponse {
  qrCode: SessionQRCode | null
}

export interface AbsencesListResponse {
  absences: Absence[]
  total?: number
}

export interface JustificationsListResponse {
  justifications: JustificationRequest[]
  total?: number
}

// Validate (approve/reject) a justification.
export interface JustificationDecisionRequest {
  decision: Exclude<JustificationDecision, "pending">
  rejectionNote?: string
}

// Filters for listing absences (student view). The reviewer queue has no
// filters: the backend only exposes the pending list.
export interface AbsenceQueryParams {
  status?: AbsenceStatus | "all"
  courseId?: string
}

// ---- Display helpers ----------------------------------------------------

export const absenceStatusConfig: Record<
  AbsenceStatus,
  { label: string; color: string; bgColor: string }
> = {
  absent: {
    label: "Absent",
    color: "text-red-600 dark:text-red-400",
    bgColor: "bg-red-500/10",
  },
  justified: {
    label: "Pending Review",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-500/10",
  },
  confirmed: {
    label: "Justified",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-500/10",
  },
}

export const justificationDecisionConfig: Record<
  JustificationDecision,
  { label: string; color: string; bgColor: string }
> = {
  pending: {
    label: "Pending",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-500/10",
  },
  approved: {
    label: "Approved",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-500/10",
  },
  rejected: {
    label: "Rejected",
    color: "text-red-600 dark:text-red-400",
    bgColor: "bg-red-500/10",
  },
}
